rule[
 ruleID "R10: ATP + Acetate + CoA <=> AMP + PPi + Ac-CoA" 
 left [
   edge [ source 2 target 4 label "-"]
   edge [ source 5 target 19 label "-"]
   edge [ source 8 target 11 label "-"]
 ] 
 context [
   node [ id 1 label "C"]
   node [ id 2 label "C"]
   node [ id 3 label "O"]
   node [ id 4 label "O"]
   node [ id 5 label "S"]
   node [ id 6 label "Ad"]
   node [ id 7 label "O"]
   node [ id 8 label "P"]
   node [ id 9 label "O"]
   node [ id 10 label "O"]
   node [ id 11 label "O"]
   node [ id 12 label "P"]
   node [ id 13 label "O"]
   node [ id 14 label "O"]
   node [ id 15 label "O"]
   node [ id 16 label "P"]
   node [ id 17 label "O"]
   node [ id 18 label "CoA"]
   node [ id 19 label "H"]
   node [ id 20 label "O"]
   node [ id 21 label "O"]
   edge [ source 1 target 2 label "-"]
   edge [ source 2 target 3 label "="]
   edge [ source 5 target 18 label "-"]
   edge [ source 6 target 7 label "-"]
   edge [ source 7 target 8 label "-"]
   edge [ source 8 target 9 label "="]
   edge [ source 8 target 10 label "-"]
   edge [ source 11 target 12 label "-"]
   edge [ source 12 target 13 label "="]
   edge [ source 12 target 14 label "-"]
   edge [ source 12 target 15 label "-"]
   edge [ source 15 target 16 label "-"]
   edge [ source 16 target 17 label "="]
   edge [ source 16 target 20 label "-"]
   edge [ source 16 target 21 label "-"] 
 ] 
 right [
   edge [ source 2 target 5 label "-"]
   edge [ source 4 target 8 label "-"]
   edge [ source 11 target 19 label "-"]
 ]
]

