rule[
 ruleID "R9: L-lysine = (3S)-3,6-diaminohexanoate" 
 left [
   edge [ source 5 target 11 label "-"]
   edge [ source 6 target 7 label "-"]
 ] 
 context [
   node [ id 1 label "N"]
   node [ id 2 label "C"]
   node [ id 3 label "C"]
   node [ id 4 label "C"]
   node [ id 5 label "C"]
   node [ id 6 label "C"]
   node [ id 7 label "N"]
   node [ id 8 label "C"]
   node [ id 9 label "O"]
   node [ id 10 label "O"]
   node [ id 11 label "H"]
   node [ id 12 label "H"]
   node [ id 13 label "H"]
   node [ id 14 label "H"]
   node [ id 15 label "H"]
   edge [ source 1 target 2 label "-"]
   edge [ source 1 target 14 label "-"]
   edge [ source 1 target 15 label "-"]
   edge [ source 2 target 3 label "-"]
   edge [ source 3 target 4 label "-"]
   edge [ source 4 target 5 label "-"]
   edge [ source 5 target 6 label "-"]
   edge [ source 6 target 8 label "-"]
   edge [ source 7 target 12 label "-"]
   edge [ source 7 target 13 label "-"]
   edge [ source 8 target 9 label "="]
   edge [ source 8 target 10 label "-"]
 ] 
 right [
   edge [ source 5 target 7 label "-"]
   edge [ source 6 target 11 label "-"]
 ]
]

