rule[
 ruleID "R3: L-Aspartate + 2-Oxoglutarate <=> Oxaloacetate + L-Glutamate" 
 left [
   edge [ source 1 target 2 label "-"]
   edge [ source 2 target 22 label "-"]
   edge [ source 15 target 16 label "="]
 ] 
 context [
   node [ id 1 label "N"]
   node [ id 2 label "C"]
   node [ id 3 label "C"]
   node [ id 4 label "C"]
   node [ id 5 label "O"]
   node [ id 6 label "O"]
   node [ id 7 label "C"]
   node [ id 8 label "O"]
   node [ id 9 label "O"]
   node [ id 10 label "O"]
   node [ id 11 label "C"]
   node [ id 12 label "O"]
   node [ id 13 label "C"]
   node [ id 14 label "C"]
   node [ id 15 label "C"]
   node [ id 16 label "O"]
   node [ id 17 label "C"]
   node [ id 18 label "O"]
   node [ id 19 label "O"]
   node [ id 20 label "H"]
   node [ id 21 label "H"]
   node [ id 22 label "H" ]
   edge [ source 1 target 20 label "-"]
   edge [ source 1 target 21 label "-"]
   edge [ source 2 target 3 label "-"]
   edge [ source 2 target 7 label "-"]
   edge [ source 3 target 4 label "-"]
   edge [ source 4 target 5 label "="]
   edge [ source 4 target 6 label "-"]
   edge [ source 7 target 8 label "="]
   edge [ source 7 target 9 label "-"]
   edge [ source 10 target 11 label "="]
   edge [ source 11 target 12 label "-"]
   edge [ source 11 target 13 label "-"]
   edge [ source 13 target 14 label "-"]
   edge [ source 14 target 15 label "-"]
   edge [ source 15 target 17 label "-"]
   edge [ source 17 target 18 label "="]
   edge [ source 17 target 19 label "-"]
 ] 
 right [
   edge [ source 15 target 22 label "-"]
   edge [ source 1 target 15 label "-"]
   edge [ source 2 target 16 label "="]
 ]
]

