rule[
 ruleID "R11: ATP + Ac-CoA + HCO3- = ADP + malonyl-CoA + Pi" 
 left [
   edge [ source 11 target 14 label "-"]
   edge [ source 20 target 21 label "-"]
   edge [ source 1 target 23 label "-"]
 ] 
 context [
   node [ id 1 label "C"]
   node [ id 2 label "C"]
   node [ id 3 label "O"]
   node [ id 4 label "S"]
   node [ id 5 label "Ad"]
   node [ id 6 label "O"]
   node [ id 7 label "P"]
   node [ id 8 label "O"]
   node [ id 9 label "O"]
   node [ id 10 label "O"]
   node [ id 11 label "P"]
   node [ id 12 label "O"]
   node [ id 13 label "O"]
   node [ id 14 label "O"]
   node [ id 15 label "P"]
   node [ id 16 label "O"]
   node [ id 17 label "O"]
   node [ id 18 label "O"]
   node [ id 19 label "O"]
   node [ id 20 label "C"]
   node [ id 21 label "O"]
   node [ id 22 label "O"]
   node [ id 23 label "H"]
   node [ id 24 label "CoA"]
   edge [ source 1 target 2 label "-"]
   edge [ source 2 target 3 label "="]
   edge [ source 2 target 4 label "-"]
   edge [ source 4 target 24 label "-"]
   edge [ source 5 target 6 label "-"]
   edge [ source 6 target 7 label "-"]
   edge [ source 7 target 8 label "="]
   edge [ source 7 target 9 label "-"]
   edge [ source 7 target 10 label "-"]
   edge [ source 10 target 11 label "-"]
   edge [ source 11 target 12 label "="]
   edge [ source 11 target 13 label "-"]
   edge [ source 14 target 15 label "-"]
   edge [ source 15 target 16 label "="]
   edge [ source 15 target 17 label "-"]
   edge [ source 15 target 18 label "-"]
   edge [ source 19 target 20 label "="]
   edge [ source 20 target 22 label "-"]
 ] 
 right [
   edge [ source 1 target 20 label "-"]
   edge [ source 11 target 21 label "-"]   
   edge [ source 14 target 23 label "-"]
 ]
]
