rule[
 ruleID " alpha-D-glucose 1-phosphate = D-glucose 6-phosphate"
 
 left [
   edge [ source 6 target 7 label "-"]
   edge [ source 9 target 10 label "-"]
   edge [ source 9 target 17 label "-"]
   edge [ source 10 target 18 label "-"]
 ]
 
 context [
   node [ id 1 label "O"]
   node [ id 2 label "P"]
   node [ id 3 label "O"]
   node [ id 4 label "O"]
   node [ id 5 label "O"]
   node [ id 6 label "C"]
   node [ id 7 label "O"]
   node [ id 8 label "C"]
   node [ id 9 label "C"]
   node [ id 10 label "O"]
   node [ id 11 label "C"]
   node [ id 12 label "O"]
   node [ id 13 label "C"]
   node [ id 14 label "O"]
   node [ id 15 label "C"]
   node [ id 16 label "O"]
   node [ id 17 label "H"]
   node [ id 18 label "H"]
   edge [ source 1 target 2 label "="]
   edge [ source 2 target 3 label "-"]
   edge [ source 2 target 4 label "-"]
   edge [ source 2 target 5 label "-"]
   edge [ source 5 target 6 label "-"]
   edge [ source 6 target 15 label "-"]
   edge [ source 7 target 8 label "-"]
   edge [ source 8 target 9 label "-"]
   edge [ source 8 target 11 label "-"]
   edge [ source 11 target 12 label "-"]
   edge [ source 11 target 13 label "-"]
   edge [ source 13 target 14 label "-"]
   edge [ source 13 target 15 label "-"]
   edge [ source 15 target 16 label "-"]
 ]
 
 right [
   edge [ source 6 target 17 label "-"]
   edge [ source 7 target 18 label "-"]
   edge [ source 9 target 10 label "="]
 ]
]