rule[
 ruleID " inositol 1-phosphate + H2O = myo-inositol + phosphate"
 
 left [
   edge [ source 1 target 18 label "-"]
   edge [ source 6 target 7 label "-"]
 ]
 
 context [
   node [ id 1 label "O"]
   node [ id 2 label "O"]
   node [ id 3 label "P"]
   node [ id 4 label "O"]
   node [ id 5 label "O"]
   node [ id 6 label "O"]
   node [ id 7 label "C"]
   node [ id 8 label "C"]
   node [ id 9 label "O"]
   node [ id 10 label "C"]
   node [ id 11 label "O"]
   node [ id 12 label "C"]
   node [ id 13 label "O"]
   node [ id 14 label "C"]
   node [ id 15 label "O"]
   node [ id 16 label "C"]
   node [ id 17 label "O"]
   node [ id 18 label "H"]
   edge [ source 2 target 3 label "="]
   edge [ source 3 target 4 label "-"]
   edge [ source 3 target 5 label "-"]
   edge [ source 3 target 6 label "-"]
   edge [ source 7 target 8 label "-"]
   edge [ source 7 target 16 label "-"]
   edge [ source 8 target 9 label "-"]
   edge [ source 8 target 10 label "-"]
   edge [ source 10 target 11 label "-"]
   edge [ source 10 target 12 label "-"]
   edge [ source 12 target 13 label "-"]
   edge [ source 12 target 14 label "-"]
   edge [ source 14 target 15 label "-"]
   edge [ source 14 target 16 label "-"]
   edge [ source 16 target 17 label "-"]
 ]
 
 right [
   edge [ source 1 target 7 label "-"]
   edge [ source 6 target 18 label "-"]
 ]
]