rule[
 ruleID " cellobiose + phosphate = alpha-D-glucose 1-phosphate + D-glucose"
 
 left [
   edge [ source 4 target 29 label "-"]
   edge [ source 10 target 11 label "-"]
 ]
 
 context [
   node [ id 1 label "O"]
   node [ id 2 label "P"]
   node [ id 3 label "O"]
   node [ id 4 label "O"]
   node [ id 5 label "O"]
   node [ id 6 label "O"]
   node [ id 7 label "C"]
   node [ id 8 label "C"]
   node [ id 9 label "O"]
   node [ id 10 label "C"]
   node [ id 11 label "O"]
   node [ id 12 label "C"]
   node [ id 13 label "C"]
   node [ id 14 label "O"]
   node [ id 15 label "C"]
   node [ id 16 label "O"]
   node [ id 17 label "C"]
   node [ id 18 label "O"]
   node [ id 19 label "O"]
   node [ id 20 label "C"]
   node [ id 21 label "C"]
   node [ id 22 label "O"]
   node [ id 23 label "C"]
   node [ id 24 label "O"]
   node [ id 25 label "C"]
   node [ id 26 label "O"]
   node [ id 27 label "C"]
   node [ id 28 label "O"]
   node [ id 29 label "H"]
   edge [ source 1 target 2 label "="]
   edge [ source 2 target 3 label "-"]
   edge [ source 2 target 4 label "-"]
   edge [ source 2 target 5 label "-"]
   edge [ source 6 target 7 label "-"]
   edge [ source 7 target 8 label "-"]
   edge [ source 8 target 9 label "-"]
   edge [ source 8 target 27 label "-"]
   edge [ source 9 target 10 label "-"]
   edge [ source 10 target 23 label "-"]
   edge [ source 11 target 12 label "-"]
   edge [ source 12 target 13 label "-"]
   edge [ source 12 target 20 label "-"]
   edge [ source 13 target 14 label "-"]
   edge [ source 13 target 15 label "-"]
   edge [ source 15 target 16 label "-"]
   edge [ source 15 target 17 label "-"]
   edge [ source 17 target 18 label "-"]
   edge [ source 17 target 19 label "-"]
   edge [ source 19 target 20 label "-"]
   edge [ source 20 target 21 label "-"]
   edge [ source 21 target 22 label "-"]
   edge [ source 23 target 24 label "-"]
   edge [ source 23 target 25 label "-"]
   edge [ source 25 target 26 label "-"]
   edge [ source 25 target 27 label "-"]
   edge [ source 27 target 28 label "-"]
 ]
 
 right [
   edge [ source 4 target 10 label "-"]
   edge [ source 11 target 29 label "-"]
 ]
]