rule[
 ruleID " D-Glucose 6-phosphate = L-myo-Inositol 1-phosphate"
 
 left [
   edge [ source 1 target 2 label "="]
   edge [ source 11 target 17 label "-"]
 ]
 
 context [
   node [ id 1 label "O"]
   node [ id 2 label "C"]
   node [ id 3 label "C"]
   node [ id 4 label "O"]
   node [ id 5 label "C"]
   node [ id 6 label "O"]
   node [ id 7 label "C"]
   node [ id 8 label "O"]
   node [ id 9 label "C"]
   node [ id 10 label "O"]
   node [ id 11 label "C"]
   node [ id 12 label "O"]
   node [ id 13 label "P"]
   node [ id 14 label "O"]
   node [ id 15 label "O"]
   node [ id 16 label "O"]
   node [ id 17 label "H"]
   edge [ source 2 target 3 label "-"]
   edge [ source 3 target 4 label "-"]
   edge [ source 3 target 5 label "-"]
   edge [ source 5 target 6 label "-"]
   edge [ source 5 target 7 label "-"]
   edge [ source 7 target 8 label "-"]
   edge [ source 7 target 9 label "-"]
   edge [ source 9 target 10 label "-"]
   edge [ source 9 target 11 label "-"]
   edge [ source 11 target 12 label "-"]
   edge [ source 12 target 13 label "-"]
   edge [ source 13 target 14 label "="]
   edge [ source 13 target 15 label "-"]
   edge [ source 13 target 16 label "-"]
 ]
 
 right [
   edge [ source 1 target 2 label "-"]
   edge [ source 1 target 17 label "-"]
   edge [ source 2 target 11 label "-"]
 ]
]